#ifndef LIBAUDIOCAPTURE_GLOBAL_H
#define LIBAUDIOCAPTURE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBAUDIOCAPTURE_LIBRARY)
#  define LIBAUDIOCAPTURE_EXPORT Q_DECL_EXPORT
#else
#  define LIBAUDIOCAPTURE_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBAUDIOCAPTURE_GLOBAL_H
